### ISSUE TITLE
Primitive to convert between Principal and AccountId

### ISSUE THREAD

**Issue by chenyan-dfinity** [dfinity/motoko#2767]
To talk with ledger canister, we need a primitive to convert between Principal and AccountId.

Related issue: https://github.com/dfinity/motoko-base/issues/236

**Comment by nomeata** [comment]
Why does this have to be a primitive? Isn't that a “simple" matter of hashing and hexencoding?

**Comment by chenyan-dfinity** [comment]
For library support, we need an intro form from blob to principal plus library for sha encoding. But `Principal.fromBlob` seems to break abstraction?

**Comment by nomeata** [comment]
Well, we have an intro form, via actor literals, but it is convoluted.

I have no qualms about adding `Blob -> Principal`, after all principals are just blobs, and have no further structure (besides, maybe, an upper size limit that such a prim might want to check).

But that's about principals, not account IDs. Oh, and unless I am mistaken, you can't convert an account id into a principal, because the other direction involves hashing?

**Comment by chenyan-dfinity** [comment]
Right, account id to principal is missing. Either we provide a primitive from blob to principal, or we provide accountId to principal conversion, which eliminates the need for external hashing library.

**Comment by nomeata** [comment]
How do you convert an account id into an principal?

**Comment by nomeata** [comment]
I think we can close this. Adding the tangentially related `Blob -> Principal` in #3050
