### ISSUE TITLE
Selective Field Import

### ISSUE THREAD

**Issue by di-wu** [dfinity/motoko#3121]
It seems you can not import a file that uses selective field imports.
- #3076 by @ggreif

---

```tree
src
├── X.mo
└── Y.mo
```

```motoko
// X.mo
import { Array_init = init } = "mo:⛔";
```

```motoko
// Y.mo
import X "X";
```

### Error
```
src/X.mo:1.8-1.29: type error [M0015], only trivial patterns allowed in static expressions
```

### Context
```
$(vessel bin)/moc --check $(vessel sources) src/Y.mo
```
- `vessel 0.6.2`
- `Motoko compiler 0.6.21 (source wahvzdqw-grg3wqkh-0n8s7fj6-f4rxx0rh)`

**Comment by nomeata** [comment]
Thanks for reporting! This needs 
updates in https://github.com/dfinity/motoko/blob/master/src/mo_frontend/static.ml to allow more kind of patterns.

I wonder if we need to be careful to not accept cyclic definitions, or if the definesdness check prevents that. But it's too late today to think this through.

**Comment by nomeata** [comment]
Also, will shouldn't allow anything in libraries that cannot be compiler strategically, i.e. is `const` in the sense of https://github.com/dfinity/motoko/blob/master/src/ir_passes/const.ml. that handles object patterns already, so we should be good here. (This is important also so that function calls into libraries will be compiled to direct calls to known functions)

**Comment by ggreif** [comment]
We already permit `TupP` in that context, can't see how allowing `ObjP` would be different. Working o a fix.

**Comment by ggreif** [comment]
Released as https://github.com/dfinity/motoko/releases/tag/0.6.22
