### ISSUE TITLE
Doc actor-classes.md examples not showing

### ISSUE THREAD

**Issue by hl11jp** [dfinity/motoko#3376]
example error at Buckets.mo

**Comment by crusso** [comment]
Thanks for reporting an issue. Can you explain what the issue is a bit more precisely?

I seem to be able to view https://internetcomputer.org/docs/current/developer-docs/build/languages/motoko/actor-classes fine in chrome, including the code examples.

![image](https://user-images.githubusercontent.com/85788/182166618-c33c31bb-8a61-4079-bfa9-1e7d3de8d2a6.png)
