### ISSUE TITLE
is it safe to just remove stable variable?

### ISSUE THREAD

**Issue by ZenVoich** [dfinity/motoko#4119]
When I remove stable var I get an error:
```
(unknown location): Compatibility error [M0169], stable variable val2 of previous type
  var [var V]
cannot be discarded; promote to type `Any` instead
```

**Comment by crusso** [comment]
It basically would be ok. The problem is that you might re-add a new variable of the same name later, forgetting that you ever had one of that name, and if you upgrade an old version of the canister that still had the old version of that variable, you might get unexpected behaviour, seeing the old, forgotten about, value instead of the one produced by the new initializer.

**Comment by crusso** [comment]
See above
